### ISSUE TITLE
Feature Request - Expand All

### ISSUE THREAD

**Issue by stworklog** [abdalmoniem/VSCode-C-Call-Hierarchy#1]
**Current pain**
Currently, the call stack is folded in default. To view the call stack, it takes many mouse clicks to trace to the main function. 

![image](https://user-images.githubusercontent.com/104875559/168332675-7b2c73d4-d192-454e-9fee-d0f41279e023.png)

To reduce the # of mouse clicks, I propose two possible suggestions for this feature request:

Feature solution option 1
Expand all function calls by default

Feature solution option 2
[right click] on the function, and then choose [Expand All].
![image](https://user-images.githubusercontent.com/104875559/168331336-58b0f3e5-ac06-415b-b476-55cc1bb59664.png)

**Comment by abdalmoniem** [comment]
Hello,

The way call hierarchy works, is the extension provides data about function calls to vscode, and vscode handles the UI/UX of these data in call hierarchy. Another approach would be creating custom views to and implement logic of UI/UX in the extension, because then any new features coming to VSCode's call hierarchy would be missed unless replicated, which is going to be a big cat and mouse game, I had solved this issue locally by adding a command to the command palette to recursively expand these functions but it was slow and unreliable, so I couldn't ship it with the extension. may be I can work on both directions. but in the meantime I think the best way to resolve this issue is to open it on Microsoft's VSCode's repository.

**Comment by stworklog** [comment]
Thank you for your explanation. Since there is nothing you can do here. I'll close the issue.
